/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.najah.ai_vrp;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

public class MainInterface extends javax.swing.JFrame {
    private final int radius = 10;
    private final ArrayList<Node> nodesList = new ArrayList<>();
    private int currentId = 0;
    private int truckCapacity = 200;
    private int numberOfTrucks = 3;
    private final Color startNodeColor = Color.YELLOW;
    private final Color normalColor = Color.WHITE;
    private boolean startNodeSet = false;
    private TruckManager trucksManager;
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        this.setTitle("VRP");
        
        Thread updateMapThread = new Thread(new Runnable() {
            public void run() {
                // Here update label name to current temp label
                updateMapContinously();
            }
        });
        Thread updateTempThread = new Thread(new Runnable() {
            public void run() {
                // Here update label name to current temp label
                updateTempContinously(jLabel5);
            }
        });
        updateTempThread.start();
        updateMapThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board1 = new Board();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        board1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                board1MouseClicked(evt);
            }
        });
        board1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Number of warehouses:");
        jPanel2.add(jLabel11);
        jLabel11.getAccessibleContext().setAccessibleName(" Number of warehouses:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);
        jLabel4.getAccessibleContext().setAccessibleName("______");

        board1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 230, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setForeground(new java.awt.Color(204, 204, 204));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        jPanel9.setLayout(flowLayout3);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Truck Capacity");
        jPanel9.add(jLabel3);

        board1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, -1, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Truck Count");
        jPanel10.add(jLabel6);

        board1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 110, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setForeground(new java.awt.Color(204, 204, 204));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Initial Temp");
        jPanel7.add(jLabel1);

        board1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Final Temp");
        jPanel6.add(jLabel2);

        board1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("3");
        jTextField4.setBorder(null);
        board1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 40, 20));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("200");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        board1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 50, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("_________________________________________");
        board1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("_________________");
        board1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("10000");
        jTextField1.setBorder(null);
        board1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 50, -1));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("900");
        jTextField2.setBorder(null);
        board1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 40, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("_________________________________________");
        board1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Optimize");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        board1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 100, 30));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("__________________");
        board1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Clear Cities");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        board1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 100, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Random Path");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        board1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 110, 30));
        jButton3.getAccessibleContext().setAccessibleName(" Random Path ");

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("_________________________________________");
        board1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("__________________");
        board1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 110, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        board1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, -1, -1));

        getContentPane().add(board1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -8, 1100, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nodesList.clear();
        jLabel4.setText(Integer.toString(nodesList.size()));
        board1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void board1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_board1MouseClicked
        // TODO add your handling code here:
        Graphics g = board1.getGraphics();
        Node node = new Node(evt.getX(), evt.getY());
        node.id = currentId;
        if(!this.startNodeSet){
            node.isStart = true;
            this.startNodeSet = true;
        }else{
            node.readCapacity();
        }
        currentId++;
        nodesList.add(node);
        jLabel4.setText(Integer.toString(nodesList.size()));
        this.drawNode(node, g);
    }//GEN-LAST:event_board1MouseClicked


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        trucksManager.initialTemp = Integer.parseInt(this.jTextField1.getText());
        trucksManager.finalTemp = Integer.parseInt(this.jTextField2.getText());
        //int maxIter = 1000;

        
        Thread pathThread = new Thread(new Runnable(){
            public void run(){
                trucksManager.FindOptimizedPaths(0);
                drawPath();
                showShipmentState(trucksManager.currentShipment);
            }
        });
        
        pathThread.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    int oldTemp = 0;
    private void updateTempContinously(JLabel label){
        while (true) {
            SimulatedAnnealing<Shipment> SA = SimulatedAnnealing.<Shipment>getInstance();
            try{
                Thread.sleep(10);
            }catch(Exception ex){
                ex.printStackTrace();
            }
            if(SA == null)
                continue;
            
            if(oldTemp == SA.currentTemp)
                continue;
            SwingUtilities.invokeLater(new Runnable() {
                public void run() { 
                
                    label.setText(Integer.toString(oldTemp));
                    oldTemp = SA.currentTemp;
                    
                }
            });
        }
    }
    
    private void updateMapContinously() {
        while (true) {
            SimulatedAnnealing<Shipment> SA = SimulatedAnnealing.<Shipment>getInstance();
            try{
                Thread.sleep(10);
            }catch(Exception ex){
                ex.printStackTrace();
            }
            if(SA == null || !SA.repaint)
                continue;
            SA.repaint = false;
            // Use SwingUtilities.invokeLater to update the JLabel on the EDT
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    drawPath();
                    
                }
            });
        }
    }
    
    private void showShipmentState(Shipment shipment){
        JTextArea textArea = new JTextArea(20, 50); // 20 rows and 50 columns
        textArea.setText(shipment.toString());
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false); // Make it read-only

        // Wrap the JTextArea in a JScrollPane
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // Show a JOptionPane with the JTextArea inside a JScrollPane
        JOptionPane.showMessageDialog(null, scrollPane, "Long Message", JOptionPane.INFORMATION_MESSAGE);
   
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            this.truckCapacity = Integer.parseInt(this.jTextField3.getText());
            this.numberOfTrucks = Integer.parseInt(this.jTextField4.getText());
            this.trucksManager = new TruckManager(this.truckCapacity, this.numberOfTrucks);
            this.trucksManager.setNodesList(nodesList);
            this.trucksManager.constructPath();
            this.drawPath();
        }catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void drawPath(){
        Graphics g = board1.getGraphics();
        board1.paint(g);
        for(Node temp:nodesList){
            this.drawNode(temp, g);
        }
        for(ArrayList<Node> paths: this.trucksManager.getDisplayPath()){
            Color randomColor = this.getRandomColor();
            g.setColor(randomColor);
            for(int i = 0; i < paths.size() - 1; i++){
                Node current = paths.get(i);
                Node next = paths.get(i+1);
                g.drawLine(current.x, current.y, next.x, next.y);
            }
        }
        Color purple = new Color(255,204,204);
        
        g.setColor(purple);
        Font verdanaBold = new Font("Verdana", Font.BOLD, 12);
        g.setFont(verdanaBold);
        g.drawString("Current Distance :"+this.trucksManager.calculateCurrentDistance(), 860, 610);
        SimulatedAnnealing<Shipment> SA = SimulatedAnnealing.<Shipment>getInstance();
        g.drawString("Current Temprature :"+ (SA == null || SA.currentTemp == 0 ? "Not started" : SA.currentTemp.toString()), 860, 635);
    }
    
    private Color getRandomColor(){
        Random rand = new Random();
        float h = rand.nextFloat();
        float s = rand.nextFloat() * 0.5f;
        float b = 0.5f + rand.nextFloat() * 0.5f;
        return Color.getHSBColor(h, s, b);
    }
    
    private void drawNode(Node temp, Graphics g){
        if(temp.isStart){
            g.setColor(this.startNodeColor);
        }else{
            g.setColor(this.normalColor);
            g.drawString(Integer.toString(temp.capacity),temp.x-radius/2, temp.y + 2*radius);
        }
        g.drawString(Integer.toString(temp.id),temp.x-radius/2, temp.y - radius);
        g.drawOval(temp.x-radius/2,temp.y-radius/2, radius, radius);
        g.fillOval(temp.x-radius/2,temp.y-radius/2, radius, radius);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
